[package]
name = "yalp-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
yalp-core = { path="../yalp-core" }
proc-macro2 = "1.0.83"
quote = "1.0.36"
syn = "2.0.65"
lazy_static = "1.4.0"
